In [2]:
import pandas as pd
import numpy as np
import ast

In [ ]:
# converting to excel for ease of use

df = pd.read_csv("FINALKB.csv")
df.to_excel("FINALKB.xlsx")

In [ ]:
# Listing out all attributes to identify 'list' based attributes.
# The objective of the preprocessing done in this notebook is to avoid special characters and failures of ast.literal_eval().

df = pd.read_csv("FINALKB.csv")
print(df.columns)

In [ ]:
# The obtained list of 'list' based attributes is 

list_attributes = [
'BOOK_EDITIONS_ENGLISH', 'BOOK_EDITIONS_TELUGU', 
'BOOK_SERIES_ENGLISH', 'BOOK_SERIES_TELUGU',
'CHARACTERS_ENGLISH', 'CHARACTERS_TELUGU', 
'BOOK_AWARDS_ENGLISH','BOOK_AWARDS_TELUGU',
'AUTHOR_AWARDS_ENGLISH', 'AUTHOR_AWARDS_TELUGU', 
'AUTHOR_NOTABLE_WORKS_ENGLISH', 'AUTHOR_NOTABLE_WORKS_TELUGU', 
'AUTHOR_OTHER_WORKS_ENGLISH', 'AUTHOR_OTHER_WORKS_TELUGU', 
'AUTHOR_GENRE_ENGLISH', 'AUTHOR_GENRE_TELUGU', 
'PUBLISHER_COLLECTION_ENGLISH', 'PUBLISHER_COLLECTION_TELUGU',
'AWARDS_AS_CATEGORY'
]

In [1]:
# Function to be directly used to find the values failing ast.literal_eval

def ast_failure(df,ATT_NAME):
    lis = []
    for i in range(0,6500):
        x = df.iloc[i][ATT_NAME]
        if pd.isnull(x)==False:
            try:
                y = ast.literal_eval(x)
            except:
                print(i,x)
                lis.append(i)
    print(lis)
    print(len(lis))

### 1) Book Editions

#### 1.1 Identifying ast.literal_eval() failing values

In [20]:
ast_failure(df,'BOOK_EDITIONS_TELUGU')

From the output, we see that values of 'BOOK_EDITIONS_TELUGU' and 'BOOK_EDITIONS_ENGLISH' at 1090, 2529, 3077, 3147, 4298, 4966, 5321 should be made null or np.nan.

In [14]:
temp = [1090, 2529, 3077, 3147, 4298, 4966, 5321]
tlis = ['BOOK_EDITIONS_TELUGU','BOOK_EDITIONS_ENGLISH']

for j in tlis:
    for i in temp:
        df.at[i,j] = np.nan

#### 1.2 Correcting the value స్ట్. to make it సెయింట్ 

In [15]:
number_of_replacements = 0

for i in range(0,6500):
    x = df.iloc[i]['BOOK_EDITIONS_TELUGU']
    if pd.isnull(x)==False:
        if 'స్ట్' in x:
            if 'స్ట్ మార్టిన్స్ ప్రెస్' in x or "స్ట్. మార్టిన్'స్ ప్రెస్" in x:
                df.at[i,'BOOK_EDITIONS_TELUGU'] = x.replace("స్ట్ మార్టిన్స్ ప్రెస్","సెయింట్ మార్టిన్స్ ప్రెస్").replace("స్ట్. మార్టిన్'స్ ప్రెస్","సెయింట్ మార్టిన్స్ ప్రెస్")
                number_of_replacements +=1
        else:
            pass
        
print("Number of replacements : {}".format(number_of_replacements))

Number of replacements : 137


### 2) Book Series

#### 2.1 Identifying ast.literal_eval() failing values

In [16]:
for i in range(0,6500):
    x = df.iloc[i]['BOOK_SERIES_TELUGU']
    if pd.isnull(x)==False:
        try:
            y = ast.literal_eval(x)
        except:
            print(i,x)

1974 ఎవ్రీమాన్ లైబ్రరీ
4298  పాత్ర సమాచారం
4368 గోళం
5321  మరియు అతని కాథలిక్ విశ్వాసం యొక్క రికవరీ.


From the output, we see that values of 'BOOK_SERIES_TELUGU' and 'BOOK_SRIES_ENGLISH' at 1974, 4298, 4368, 5321 should be made null or np.nan.

In [17]:
temp = [1974, 4298, 4368, 5321]
tlis = ['BOOK_SERIES_TELUGU','BOOK_SERIES_ENGLISH']

for j in tlis:
    for i in temp:
        df.at[i,j] = np.nan

### 3) Characters

#### 3.1 Identifying ast.literal_eval() failing values

In [24]:
ast_failure(df,'CHARACTERS_TELUGU')

3147 రాండమ్ హౌస్ వాల్యూ పబ్లిషింగ్
4298  సైడ్ క్వెస్ట్ లు


In [25]:
temp = [3147, 4298]
tlis = ['CHARACTERS_TELUGU','CHARACTERS_ENGLISH']

for j in tlis:
    for i in temp:
        df.at[i,j] = np.nan

### Continuing to check failure of ast.literal_eval() in all attributes

In [26]:
ast_failure(df,'BOOK_AWARDS_TELUGU')

4298  ఐటమ్ జాబితాలు
5321 కాథలిక్ బుక్ పబ్లిషింగ్ కార్పొరేషన్


In [27]:
temp = [4298, 5321]
tlis = ['BOOK_AWARDS_TELUGU','BOOK_AWARDS_ENGLISH']

for j in tlis:
    for i in temp:
        df.at[i,j] = np.nan

In [30]:
ast_failure(df,'AUTHOR_AWARDS_TELUGU')

357 National Humanities Medal
1090 కింగ్'స్ కాలేజ్ లాండన్
1974 ఐర్లాండ్
2529 పసదేన సిటీ కాలేజ్
3147 జాక్ లాండన్
4368 ఆస్ట్రేలియా
4966 బ్రీఘం యంగ్ యూనివర్సిటీ
[357, 1090, 1974, 2529, 3147, 4368, 4966]


In [31]:
temp = [357, 1090, 1974, 2529, 3147, 4368, 4966]
tlis = ['AUTHOR_AWARDS_TELUGU','AUTHOR_AWARDS_ENGLISH']

for j in tlis:
    for i in temp:
        df.at[i,j] = np.nan

In [32]:
ast_failure(df,'AUTHOR_NOTABLE_WORKS_TELUGU')

1974 ట్రినిటీ కాలేజ్ డబ్లిన్
3147 యునైటెడ్ స్టేట్స్ ఆఫ్ అమెరికా
4368 యూనివర్సిటీ ఆఫ్ సైడ్నీ
5321 సైంట్ ఆగ్సుస్టిన్','జోసెఫ్ లెల్లు
[1974, 3147, 4368, 5321]


In [33]:
temp = [1974, 3147, 4368, 5321]
tlis = ['AUTHOR_NOTABLE_WORKS_TELUGU','AUTHOR_NOTABLE_WORKS_ENGLISH']

for j in tlis:
    for i in temp:
        df.at[i,j] = np.nan

In [34]:
ast_failure(df,'AUTHOR_OTHER_WORKS_TELUGU')

3147 యూనివర్సిటీ ఆఫ్ కాలిఫోర్నియా, బర్కెలెలీ
5321 అల్జీరియా
[3147, 5321]


In [35]:
temp = [3147, 5321]
tlis = ['AUTHOR_OTHER_WORKS_TELUGU','AUTHOR_OTHER_WORKS_ENGLISH']

for j in tlis:
    for i in temp:
        df.at[i,j] = np.nan

In [38]:
ast_failure(df,'AUTHOR_GENRE_TELUGU')

87 ['కల్పన', 'ఆత్మకథ కల్పన', 'విమర్శ, వ్యాఖ్యానం', 'వ్యక్తిగత కరస్పాండెన్స్', 'జీవిత చరిత్రలు]]
308 ['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు]]
309 ['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు]]
315 ['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు]]
342 ['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు]]
395 ['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు]]
663 ['జీవిత చరిత్రలు', 'వ్యక్తిగత కథనాలు' ఇటాలియన్ ',' వ్యక్తిగత కథనాలు ',' ఆత్మకథలు ',' కల్పన ']
720 ['జీవిత చరిత్రలు', 'వ్యక్తిగత కథనాలు' ఇటాలియన్ ',' వ్యక్తిగత కథనాలు ',' ఆత్మకథలు ',' కల్పన ']
860 ['కల్పన', 'నవలలు', 'రొమాన్స్ ఫిక్షన్', 'విమర్శ, వ్యాఖ్యానం', 'జీవిత చరిత్రలు]]
1031 ['కల్పన', 'చరిత్ర', 'విమర్శ, వ్యాఖ్యానం', 'దేశీయ కల్పన', 'జీవిత చరిత్రలు]]
1134 ['కవితలు', 'విమర్శ, వ్యాఖ్యానం', 'హ్యాండ్‌బుక్‌లు మరియు మాన్యువల్లు', 'కల్పన', 'జీవిత చరిత్రలు]]
1597 ['జీవిత చరిత్రలు', 'చరిత్ర', 'మిలిటరీ చరిత్ర', 'నిజమైన నేర

In [39]:
temp = [87, 308, 309, 315, 342, 395, 663, 720, 860, 1031, 1134, 1597, 1865, 1976, 2035, 2147, 2165, 2339, 2352, 2416, 2937, 3088, 3325, 3820, 3822, 3823, 3825, 3826, 3827, 3830, 3927, 3933, 3934, 3959, 4064, 4065, 4066, 4368, 4739, 4766, 4767, 4902, 4903, 4904, 4923, 5203, 5204, 5205, 5219, 5479, 5838, 6284]
tlis = ['AUTHOR_GENRE_TELUGU']

for j in tlis:
    for i in temp:
        print(df.iloc[i]['AUTHOR_GENRE_TELUGU'])
        n = input()
        if n=="-1":
            df.at[i,j] = np.nan
        else:
            df.at[i,j] = n

['కల్పన', 'ఆత్మకథ కల్పన', 'విమర్శ, వ్యాఖ్యానం', 'వ్యక్తిగత కరస్పాండెన్స్', 'జీవిత చరిత్రలు]]
['కల్పన', 'ఆత్మకథ కల్పన', 'విమర్శ వ్యాఖ్యానం', 'వ్యక్తిగత కరస్పాండెన్స్', 'జీవిత చరిత్రలు']
['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు]]
['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు']
['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు]]
['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు']
['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు]]
['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు']
['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు]]
['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు']
['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు]]
['కల్పన', 'జీవిత చరిత్రలు', 'మానసిక కల్పన', 'చిన్న కథలు', 'జానపద కథలు']
['జీవిత చరిత్రలు', 'వ్యక్తిగత కథనాలు' ఇటాలియన్ ',' వ్యక్తిగత కథనాలు ',' ఆత్మకథలు ',' కల్పన ']
[

In [40]:
ast_failure(df,'AUTHOR_GENRE_TELUGU')

[]
0


In [41]:
ast_failure(df,'PUBLISHER_COLLECTION_TELUGU')

4298 Dan Birlew
[4298]
1


In [42]:
df.at[4298,'PUBLISHER_COLLECTION_TELUGU'] = np.nan
df.at[4298,'PUBLISHER_COLLECTION_ENGLISH'] = np.nan

In [43]:
ast_failure(df,'AWARDS_AS_CATEGORY')

[]
0


In [3]:
#Checking

astlis = [
 'BOOK_EDITIONS_TELUGU', 
'BOOK_SERIES_TELUGU',
'CHARACTERS_TELUGU', 
'BOOK_AWARDS_TELUGU',
'AUTHOR_AWARDS_TELUGU', 
'AUTHOR_NOTABLE_WORKS_TELUGU', 
'AUTHOR_OTHER_WORKS_TELUGU', 
'AUTHOR_GENRE_TELUGU', 
'PUBLISHER_COLLECTION_TELUGU',
'AWARDS_AS_CATEGORY'
]

for i in astlis:
    ast_failure(df,i)

NameError: name 'df' is not defined

In [46]:
df.to_csv("FINALKB_v2.csv")

### 4) Replacing తె with ది of in all values and other special character replacements

In [75]:
list_attributes = [
'BOOK_EDITIONS_TELUGU', 
'BOOK_SERIES_TELUGU',
'CHARACTERS_TELUGU', 
'BOOK_AWARDS_TELUGU',
'AUTHOR_AWARDS_TELUGU', 
 'AUTHOR_NOTABLE_WORKS_TELUGU', 
'AUTHOR_OTHER_WORKS_TELUGU', 
 'AUTHOR_GENRE_TELUGU', 
 'PUBLISHER_COLLECTION_TELUGU',
'AWARDS_AS_CATEGORY'
]

# df = pd.read_csv("FINALKB_v2.csv")
# for i in range(0,6500):
#     x = df.iloc[i]['PUBLISHER_COLLECTION_TELUGU']
#     if pd.isnull(x)==False:
# #         print(i,x)
#         if "-తె-" in x:
#             df.at[i,'PUBLISHER_COLLECTION_TELUGU'] = x.replace("-తె-","-ది-")
        

In [79]:
char_lis = []

for j in list_attributes:
    for i in range(0,6500):
        x = df.iloc[i][j]
        if pd.isnull(x)==False:
            for k in x:
                char_lis.append(k)
                
char_lis = list(sorted(list(set(char_lis))))
temp = ['/','!', '#', '$', '%', '&','.','（', '）',' ','  ','   ','    ','     ','      ','—','-','[', '\\', ']','\n','\t',"'",'"',')','(','}','{','|',',',',','４', '６', '８','0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'ீ', '்', 'ం', 'ః', 'అ', 'ఆ', 'ఇ', 'ఈ', 'ఉ', 'ఊ', 'ఋ', 'ఎ', 'ఏ', 'ఐ', 'ఒ', 'ఓ', 'ఔ', 'క', 'ఖ', 'గ', 'ఘ', 'చ', 'ఛ', 'జ', 'ఝ', 'ఞ', 'ట', 'ఠ', 'డ', 'ఢ', 'ణ', 'త', 'థ', 'ద', 'ధ', 'న', 'ప', 'ఫ', 'బ', 'భ', 'మ', 'య', 'ర', 'ల', 'ళ', 'వ', 'శ', 'ష', 'స', 'హ', 'ా', 'ి', 'ీ', 'ు', 'ూ', 'ృ', 'ె', 'ే', 'ై', 'ొ', 'ో', 'ౌ', '్', 'ౖ', '\u200b', '\u200c', '‐', '–', '—', '’', '“', '”', '…', '⁻', '₊']
            
final_char_lis = []

for i in char_lis:
    if i not in temp:
        final_char_lis.append(i)
        
print(final_char_lis)

['*', '+', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '^', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '~', '¡', '®', '¿', 'ß', 'à', 'á', 'â', 'ã', 'ä', 'å', 'æ', 'ç', 'è', 'é', 'ê', 'ë', 'ì', 'í', 'î', 'ï', 'ð', 'ñ', 'ò', 'ó', 'ô', 'ö', 'ø', 'ú', 'û', 'ü', 'þ', 'ă', 'ą', 'ć', 'č', 'đ', 'ē', 'ę', 'ī', 'ı', 'ł', 'ń', 'ō', 'ő', 'ś', 'ş', 'š', 'ţ', 'ū', 'ź', 'ż', 'ž', 'ș', 'ʹ', 'ʻ', 'ʼ', '́', '̆', '̇', '̉', '̛', 'α', 'β', 'γ', 'δ', 'ε', 'η', 'θ', 'ι', 'κ', 'λ', 'ν', 'ξ', 'ο', 'ρ', 'ς', 'σ', 'τ', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'є', 'і', 'ա', 'լ', 'ն', 'ո', 'պ', '־', 'א', 'ב', 'ג', 'ה', 'ו', 'ז', 'י', 'כ', 'ל', 'ם', 'מ', 'ן', 'נ', 'ר', 'ש', 'ת', '،', 'ؤ',

In [80]:

for j in list_attributes:
    for i in range(0,6500):
        x = df.iloc[i][j]
        if pd.isnull(x)==False:
            for k in x:
                if k in final_char_lis:
                    x = x.replace(k,"")
            df.at[i,j] = x

df.to_csv("FINALKB_v3.csv")

In [6]:
df = pd.read_csv("FINALKB_v3.csv")
for i in range(6499,5500,-1):
    print(df.iloc[i]['BOOK_EDITIONS_TELUGU'])
    

nan
nan
[['9780345342966', 'పేపర్‌బ్యాక్', 'బాలెంటిన్ బుక్స్', '1988', '179'], ['9783150092705', 'పేపర్‌బ్యాక్', 'రెక్లాం', '1991', '246'], ['9783060311354', 'పేపర్‌బ్యాక్', 'కార్నెల్సెన్', '2005', '168'], ['9780345410016', 'ట్రేడ్ పేపర్‌బ్యాక్', 'బాల్లంటిన్ బుక్స్', '1996', '179'], ['9780006546061', 'పేపర్‌బ్యాక్', 'ఫ్లామింగో', '1993', '172'], ['9780743247221', 'హార్డ్‌కవర్', 'సిమోన్ & శుస్త్తర్', '23  2003', '190'], ['9780671870362', 'హార్డ్‌కవర్', 'సిమోన్ & శుస్త్తర్', ' 1993', '190'], ['9780395878064', 'హార్డ్‌కవర్', 'ఎంక్డౌగల్ లిట్టెల్', ' 1998', '216'], ['9781597227162', 'ట్రేడ్ పేపర్‌బ్యాక్', 'వీలర్ పబ్.', '19  2008', '223'], ['9780881030198', 'హార్డ్‌కవర్', 'బాల్లంటిన్ బుక్స్', '1999', '190'], ['9780606006286', 'హార్డ్‌కవర్', 'డెంకో మీడియా', ' 1995', '179'], ['9780812415551', 'హార్డ్‌కవర్', 'గ్రాఫ్టన్ బుక్స్', '1977', '158']]
[['—', 'పేపర్‌బ్యాక్', 'సిటాడెల్ ప్రెస్', '1947', '339'], ['9781480443808', 'పేపర్‌బ్యాక్', 'ఓపెన్ రోడ్ ఇంటెగ్రేటెడ్ మీడియా, ఇంకోర్పోరాటెడ్', ' 2015', '21

In [21]:
import pandas as pd

c = 0
df = pd.read_csv("FINALKB_v3.csv")
# lis containing expletives for checking with each book title and summary. Removed.
finlis = []
for i in range(0,6500):
    flag = 0
    x = df.iloc[i]['BOOK_TITLE_ENGLISH']
    if pd.isnull(x)==False:
        for j in lis:
            if j in x:
                if 'Virginia' in x or 'virginia' in x:
                    pass
                else:
                    flag += 1
                    break
                
    y = df.iloc[i]['BOOK_SUMMARY_ENGLISH']
    if pd.isnull(y)==False:
        for j in lis:
            if j in y:
                if 'Virginia' in y or 'virginia' in y:
                    pass
                else:
                    flag += 1
                    break
                
    if flag>0:
        c+=1
        finlis.append(i)
    
print(finlis)
print(c)

[18, 80, 82, 124, 135, 153, 161, 172, 181, 195, 206, 213, 214, 227, 238, 253, 278, 283, 289, 296, 300, 316, 324, 341, 343, 349, 372, 387, 392, 422, 497, 530, 536, 537, 540, 547, 562, 588, 592, 613, 615, 628, 630, 631, 638, 644, 649, 655, 675, 688, 710, 712, 718, 724, 788, 789, 790, 801, 816, 824, 834, 845, 864, 882, 886, 920, 960, 1004, 1051, 1087, 1099, 1113, 1132, 1191, 1216, 1233, 1239, 1241, 1253, 1266, 1268, 1269, 1376, 1377, 1399, 1416, 1423, 1433, 1434, 1443, 1456, 1474, 1475, 1480, 1490, 1494, 1499, 1501, 1533, 1540, 1543, 1546, 1562, 1565, 1594, 1595, 1598, 1601, 1650, 1673, 1678, 1703, 1711, 1726, 1727, 1739, 1743, 1746, 1747, 1750, 1752, 1779, 1780, 1792, 1795, 1809, 1849, 1853, 1863, 1872, 1873, 1927, 1930, 1942, 1961, 1969, 1983, 2006, 2036, 2045, 2048, 2057, 2069, 2106, 2116, 2120, 2121, 2124, 2167, 2180, 2186, 2189, 2205, 2213, 2219, 2224, 2227, 2231, 2236, 2242, 2247, 2277, 2284, 2299, 2304, 2311, 2330, 2382, 2389, 2490, 2502, 2518, 2526, 2535, 2538, 2540, 2542, 2543, 2

In [19]:
print(df.iloc[4190]['BOOK_SUMMARY_ENGLISH'])

The story of Ennis del Mar and Jack Twist, two cowboys who share a small tent while working as herders and camp tenders during a summer spent on a range far above the tree line. They fall into a relationship that at first seems solely sexual but then reveals itself to be something more. Both men marry and have families, but over the course of many years and frequent separations they find their relationship becomes the most important thing in both their lives, and they do anything they can to maintain it. Proulx's description of their bond is beautiful and haunting and often brutal in its portrayal of the hardships, and ultimately the violence, they face.… (more)


In [17]:
c = 0
for i in range(0,6500):
    x = df.iloc[i]['BOOK_SUMMARY_TELUGU']
    if pd.isnull(x)==False and "&'91;" in x:
        print(i)
print(c)

6106
6112
0


In [22]:
# books to be removed

lis = [18, 80, 82, 124, 135, 153, 161, 172, 181, 195, 206, 213, 214, 227, 238, 253, 278, 283, 289, 296, 300, 316, 324, 341, 343, 349, 372, 387, 392, 422, 497, 530, 536, 537, 540, 547, 562, 588, 592, 613, 615, 628, 630, 631, 638, 644, 649, 655, 675, 688, 710, 712, 718, 724, 788, 789, 790, 801, 816, 824, 834, 845, 864, 882, 886, 920, 960, 1004, 1051, 1087, 1099, 1113, 1132, 1191, 1216, 1233, 1239, 1241, 1253, 1266, 1268, 1269, 1376, 1377, 1399, 1416, 1423, 1433, 1434, 1443, 1456, 1474, 1475, 1480, 1490, 1494, 1499, 1501, 1533, 1540, 1543, 1546, 1562, 1565, 1594, 1595, 1598, 1601, 1650, 1673, 1678, 1703, 1711, 1726, 1727, 1739, 1743, 1746, 1747, 1750, 1752, 1779, 1780, 1792, 1795, 1809, 1849, 1853, 1863, 1872, 1873, 1927, 1930, 1942, 1961, 1969, 1983, 2006, 2036, 2045, 2048, 2057, 2069, 2106, 2116, 2120, 2121, 2124, 2167, 2180, 2186, 2189, 2205, 2213, 2219, 2224, 2227, 2231, 2236, 2242, 2247, 2277, 2284, 2299, 2304, 2311, 2330, 2382, 2389, 2490, 2502, 2518, 2526, 2535, 2538, 2540, 2542, 2543, 2549, 2554, 2653, 2682, 2781, 2801, 2811, 2829, 2850, 2860, 2875, 2905, 2913, 2915, 2955, 2958, 2968, 2969, 2970, 2974, 2999, 3035, 3073, 3093, 3113, 3117, 3122, 3123, 3163, 3182, 3194, 3200, 3207, 3256, 3265, 3315, 3318, 3332, 3339, 3358, 3370, 3379, 3382, 3397, 3402, 3403, 3407, 3457, 3463, 3470, 3488, 3555, 3558, 3590, 3600, 3603, 3605, 3613, 3615, 3618, 3640, 3655, 3658, 3664, 3672, 3689, 3737, 3757, 3768, 3784, 3792, 3795, 3811, 3815, 3817, 3820, 3832, 3840, 3844, 3845, 3850, 3860, 3867, 3885, 3891, 3924, 3966, 3993, 4045, 4070, 4078, 4079, 4091, 4098, 4136, 4138, 4158, 4168, 4169, 4178, 4180, 4185, 4186, 4190, 4194, 4198, 4199, 4200, 4241, 4342, 4379, 4392, 4430, 4431, 4433, 4483, 4493, 4524, 4566, 4568, 4569, 4579, 4586, 4596, 4635, 4677, 4679, 4706, 4737, 4738, 4740, 4749, 4765, 4766, 4767, 4775, 4816, 4899, 4978, 5026, 5034, 5051, 5077, 5111, 5165, 5191, 5217, 5223, 5226, 5239, 5254, 5260, 5305, 5321, 5353, 5355, 5363, 5371, 5391, 5420, 5457, 5474, 5477, 5515, 5517, 5539, 5541, 5634, 5635, 5636, 5639, 5645, 5660, 5665, 5666, 5668, 5719, 5743, 5776, 5785, 5827, 5839, 5861, 5862, 5864, 5895, 5896, 5905, 5928, 5963, 5982, 5997, 5998, 5999, 6000, 6009, 6020, 6032, 6106, 6112, 6115, 6142, 6179, 6197, 6201, 6203, 6224, 6241, 6242, 6254, 6260, 6267, 6269, 6284, 6291, 6302, 6311, 6321, 6336, 6339, 6361, 6375, 6447, 6448, 6458, 6464, 6488]
print(len(lis))

405
